[project]
name = "suspension-kinematics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marshmallow-dataclass>=8.7.1",
    "numpy>=2.2.0",
    "pyyaml>=6.0.2",
    "ruff>=0.8.3",
]

[tool.uv.workspace]
members = ["kinematics"]
