[project]
name = "suspension-kinematics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marshmallow-dataclass>=8.7.1",
    "matplotlib>=3.10.0",
    "numpy>=2.2.0",
    "pytest-dotenv>=0.5.2",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
    "ruff>=0.8.3",
    "scipy>=1.14.1",
]

[project.optional-dependencies]
plot = [
    "matplotlib>=3.10.0",
    "pyqt5>=5.15.11",
]

[tool.uv.workspace]
members = ["kinematics"]
